services:
  app_laravel_po:
    container_name: "app_laravel_po"
    build: .
    volumes:
      - .:/var/www
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - laravel
  
  webserver_laravel_po:
    image: nginx:alpine
    container_name: webserver_laravel_po
    restart: unless-stopped
    ports:
      - "7080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  db_laravel_po:
    container_name: "db_laravel_po"
    image: mysql:8.4
    ports:
      - "7306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'laravel' # TODO: Change this
      MYSQL_USER: 'adrian'
      MYSQL_PASS: 'laravel'
      TZ: 'Asia/Jakarta'
    command: ['--default-time-zone=+07:00','--mysql-native-password=ON']
    volumes:
      - ./sql_init/laravel_20260202.sql:/docker-entrypoint-initdb.d/laravel_20260202.sql
      - ./sql_init/p2p_20260202.sql:/docker-entrypoint-initdb.d/p2p_20260202.sql
      - datavolume-laravel-po:/var/lib/mysql
    networks:
      - laravel
    restart: unless-stopped

volumes:
    datavolume-laravel-po:

networks:
  laravel:
    driver: bridge